### PR TITLE
Use comment color for inline-hints

### LINKED ISSUE #13: consider changing `ui.virtual.inlay-hint`
This is how helix looks with inlay hint enabled
image

I cannot see them tbh, i don't know how that can addect the rest of the UI, i'm just suggesting thing here
I'm using [stylix](https://github.com/danth/stylix) for this so i cannot easily modify the theme myself
PS: the theme is not modified between this repo and my pc, that's why i'm reporting this here

### PR DESCRIPTION
**Pull request by LennyPenny**
Currently, they are a background color and unreadable 

fixes #13

### CODE REVIEW

**Review by krgn — APPROVED** [review]
Thank you 🙏

**Comment by LennyPenny** [comment]
@krgn is there a way you could force the update gh action to run, so the themes are regenerated?

**Comment by krgn** [comment]
> @krgn is there a way you could force the update gh action to run, so the themes are regenerated?

Apologies, I don't know off the top of my head and I don't have computer to check this right now. 🙈😄

**Comment by LennyPenny** [comment]
image
For reference. 

I'm trying to get it running on my fork, if I succeed I'll make a pr with the results.

**Comment by JamyGolden** [comment]
@LennyPenny I've manually run the action, so themes have been updated.

**Pull request merged**
